/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author leona
 */
public class Cartelera extends javax.swing.JFrame {

    /**
     * Creates new form Cartelera
     */
    public Cartelera() {
        initComponents();
        setTitle("Cartelera de películas");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelPrincipal = new javax.swing.JPanel();
        panelPelicula4 = new javax.swing.JPanel();
        btnHorario4 = new javax.swing.JButton();
        panelHorarios3 = new javax.swing.JPanel();
        panelPelicula3 = new javax.swing.JPanel();
        btnHorario3 = new javax.swing.JButton();
        panelHorarios2 = new javax.swing.JPanel();
        panelPelicula2 = new javax.swing.JPanel();
        btnHorario2 = new javax.swing.JButton();
        panelHorarios1 = new javax.swing.JPanel();
        generoPelicula2 = new javax.swing.JLabel();
        imagenPelicula1 = new javax.swing.JLabel();
        tituloPelicula1 = new javax.swing.JLabel();
        generoPelicula1 = new javax.swing.JLabel();
        imagenPelicula2 = new javax.swing.JLabel();
        tituloPelicula2 = new javax.swing.JLabel();
        imagenPelicula3 = new javax.swing.JLabel();
        tituloPelicula3 = new javax.swing.JLabel();
        generoPelicula3 = new javax.swing.JLabel();
        imagenPelicula4 = new javax.swing.JLabel();
        tituloPelicula4 = new javax.swing.JLabel();
        generoPelicula4 = new javax.swing.JLabel();
        panelDatos = new javax.swing.JPanel();
        comboCiudad1 = new javax.swing.JComboBox<>();
        comboCine1 = new javax.swing.JComboBox<>();
        comboFecha1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        panelPelicula1 = new javax.swing.JPanel();
        btnHorario1 = new javax.swing.JButton();
        panelHorarios = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        panelPelicula4.setMaximumSize(new java.awt.Dimension(350, 200));
        panelPelicula4.setMinimumSize(new java.awt.Dimension(350, 200));
        panelPelicula4.setPreferredSize(new java.awt.Dimension(350, 200));
        panelPelicula4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHorario4.setText("Horarios:");
        btnHorario4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnHorario4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHorario4ActionPerformed(evt);
            }
        });
        panelPelicula4.add(btnHorario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        panelHorarios3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));
        panelHorarios3.setLayout(new java.awt.GridLayout(0, 3, 5, 5));
        panelPelicula4.add(panelHorarios3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 220, 180));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelPrincipal.add(panelPelicula4, gridBagConstraints);

        panelPelicula3.setMaximumSize(new java.awt.Dimension(350, 200));
        panelPelicula3.setMinimumSize(new java.awt.Dimension(350, 200));
        panelPelicula3.setPreferredSize(new java.awt.Dimension(350, 200));
        panelPelicula3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHorario3.setText("Horarios:");
        btnHorario3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnHorario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHorario3ActionPerformed(evt);
            }
        });
        panelPelicula3.add(btnHorario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        panelHorarios2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));
        panelHorarios2.setLayout(new java.awt.GridLayout(0, 3, 5, 5));
        panelPelicula3.add(panelHorarios2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 220, 180));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelPrincipal.add(panelPelicula3, gridBagConstraints);

        panelPelicula2.setMaximumSize(new java.awt.Dimension(350, 200));
        panelPelicula2.setMinimumSize(new java.awt.Dimension(350, 200));
        panelPelicula2.setPreferredSize(new java.awt.Dimension(350, 200));
        panelPelicula2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHorario2.setText("Horarios:");
        btnHorario2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnHorario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHorario2ActionPerformed(evt);
            }
        });
        panelPelicula2.add(btnHorario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        panelHorarios1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));
        panelHorarios1.setLayout(new java.awt.GridLayout(0, 3, 5, 5));
        panelPelicula2.add(panelHorarios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 220, 180));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelPrincipal.add(panelPelicula2, gridBagConstraints);

        generoPelicula2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        generoPelicula2.setForeground(new java.awt.Color(15, 25, 45));
        generoPelicula2.setText("Género: Acción");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 10);
        panelPrincipal.add(generoPelicula2, gridBagConstraints);

        imagenPelicula1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pelicula1.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        panelPrincipal.add(imagenPelicula1, gridBagConstraints);

        tituloPelicula1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        tituloPelicula1.setForeground(new java.awt.Color(15, 25, 45));
        tituloPelicula1.setText("Título: Karate Kid Legends");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        panelPrincipal.add(tituloPelicula1, gridBagConstraints);

        generoPelicula1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        generoPelicula1.setForeground(new java.awt.Color(15, 25, 45));
        generoPelicula1.setText("Género: Drama");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        panelPrincipal.add(generoPelicula1, gridBagConstraints);

        imagenPelicula2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pelicula2.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 0);
        panelPrincipal.add(imagenPelicula2, gridBagConstraints);

        tituloPelicula2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        tituloPelicula2.setForeground(new java.awt.Color(15, 25, 45));
        tituloPelicula2.setText("Título: Misión Imposible Sentencia final");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 10);
        panelPrincipal.add(tituloPelicula2, gridBagConstraints);

        imagenPelicula3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pelicula3.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(13, 10, 0, 0);
        panelPrincipal.add(imagenPelicula3, gridBagConstraints);

        tituloPelicula3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        tituloPelicula3.setForeground(new java.awt.Color(15, 25, 45));
        tituloPelicula3.setText("Título: Superman");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        panelPrincipal.add(tituloPelicula3, gridBagConstraints);

        generoPelicula3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        generoPelicula3.setForeground(new java.awt.Color(15, 25, 45));
        generoPelicula3.setText("Género: Superhéroes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        panelPrincipal.add(generoPelicula3, gridBagConstraints);

        imagenPelicula4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pelicula4.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 0);
        panelPrincipal.add(imagenPelicula4, gridBagConstraints);

        tituloPelicula4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        tituloPelicula4.setForeground(new java.awt.Color(15, 25, 45));
        tituloPelicula4.setText("Título: Jurassic World");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 0);
        panelPrincipal.add(tituloPelicula4, gridBagConstraints);

        generoPelicula4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        generoPelicula4.setForeground(new java.awt.Color(15, 25, 45));
        generoPelicula4.setText("Género: Acción");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        panelPrincipal.add(generoPelicula4, gridBagConstraints);

        panelDatos.setLayout(new java.awt.GridBagLayout());

        comboCiudad1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chimbote", "Trujillo", "Lima", "Chiclayo" }));
        comboCiudad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCiudad1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 50, 0);
        panelDatos.add(comboCiudad1, gridBagConstraints);

        comboCine1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 50, 10);
        panelDatos.add(comboCine1, gridBagConstraints);

        comboFecha1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 50, 10);
        panelDatos.add(comboFecha1, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("La función perfecta para ti.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        panelDatos.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelPrincipal.add(panelDatos, gridBagConstraints);

        panelPelicula1.setMaximumSize(new java.awt.Dimension(350, 200));
        panelPelicula1.setMinimumSize(new java.awt.Dimension(350, 200));
        panelPelicula1.setPreferredSize(new java.awt.Dimension(350, 200));
        panelPelicula1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHorario1.setText("Horarios:");
        btnHorario1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnHorario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHorario1ActionPerformed(evt);
            }
        });
        panelPelicula1.add(btnHorario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        panelHorarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));
        panelHorarios.setLayout(new java.awt.GridLayout(0, 3, 5, 5));
        panelPelicula1.add(panelHorarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 220, 180));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelPrincipal.add(panelPelicula1, gridBagConstraints);

        jScrollPane1.setViewportView(panelPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comboCiudad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCiudad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCiudad1ActionPerformed

    private void btnHorario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHorario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHorario1ActionPerformed

    private void btnHorario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHorario2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHorario2ActionPerformed

    private void btnHorario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHorario3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHorario3ActionPerformed

    private void btnHorario4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHorario4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHorario4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cartelera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHorario1;
    private javax.swing.JButton btnHorario2;
    private javax.swing.JButton btnHorario3;
    private javax.swing.JButton btnHorario4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboCine1;
    private javax.swing.JComboBox<String> comboCiudad1;
    private javax.swing.JComboBox<String> comboFecha1;
    private javax.swing.JLabel generoPelicula1;
    private javax.swing.JLabel generoPelicula2;
    private javax.swing.JLabel generoPelicula3;
    private javax.swing.JLabel generoPelicula4;
    private javax.swing.JLabel imagenPelicula1;
    private javax.swing.JLabel imagenPelicula2;
    private javax.swing.JLabel imagenPelicula3;
    private javax.swing.JLabel imagenPelicula4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelHorarios;
    private javax.swing.JPanel panelHorarios1;
    private javax.swing.JPanel panelHorarios2;
    private javax.swing.JPanel panelHorarios3;
    private javax.swing.JPanel panelPelicula1;
    private javax.swing.JPanel panelPelicula2;
    private javax.swing.JPanel panelPelicula3;
    private javax.swing.JPanel panelPelicula4;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JLabel tituloPelicula1;
    private javax.swing.JLabel tituloPelicula2;
    private javax.swing.JLabel tituloPelicula3;
    private javax.swing.JLabel tituloPelicula4;
    // End of variables declaration//GEN-END:variables
}
