/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Enumeradores.EstadoAsiento;
import javax.swing.JButton;
import javax.swing.JFrame;
import modelo.Asiento;

/**
 *
 * @author leona
 */
public class SelecciónButacas extends javax.swing.JFrame {

    /**
     * Creates new form SelecciónButacas
     */
    public SelecciónButacas() {
        initComponents();
        setTitle("Selección de Butacas");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
    }
    
    public void setDatosPelicula(String titulo, String cine, String fecha, String hora) {
    // Este método toma los datos como texto y los pone en los JLabels correspondientes.
        
    lblTituloData.setText(titulo);
    lblCineData.setText(cine);
    lblFechaData.setText(fecha);
    lblHoraData.setText(hora);
}
    
    private class AsientoVisual {
    public JButton boton;
    public Asiento modeloAsiento; // Tu clase del paquete modelo
    public EstadoAsiento estado;

    public AsientoVisual(JButton boton, Asiento modeloAsiento) {
        this.boton = boton;
        this.modeloAsiento = modeloAsiento;
        this.estado = EstadoAsiento.LIBRE; // Estado inicial por defecto
    }
}
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        panelPantalla = new javax.swing.JPanel();
        labelPantalla = new javax.swing.JLabel();
        panelDatosPelicula = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblTituloData = new javax.swing.JLabel();
        lblCine = new javax.swing.JLabel();
        lblCineData = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblFechaData = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblHoraData = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        panelButacas = new javax.swing.JPanel();
        btnAsiento1 = new javax.swing.JButton();
        btnAsiento2 = new javax.swing.JButton();
        btnAsiento3 = new javax.swing.JButton();
        btnAsiento4 = new javax.swing.JButton();
        btnAsiento5 = new javax.swing.JButton();
        btnAsiento6 = new javax.swing.JButton();
        btnAsiento7 = new javax.swing.JButton();
        btnAsiento8 = new javax.swing.JButton();
        btnAsiento9 = new javax.swing.JButton();
        btnAsiento10 = new javax.swing.JButton();
        btnAsiento11 = new javax.swing.JButton();
        btnAsiento12 = new javax.swing.JButton();
        btnAsiento13 = new javax.swing.JButton();
        btnAsiento14 = new javax.swing.JButton();
        btnAsiento15 = new javax.swing.JButton();
        btnAsiento16 = new javax.swing.JButton();
        btnAsiento17 = new javax.swing.JButton();
        btnAsiento18 = new javax.swing.JButton();
        btnAsiento19 = new javax.swing.JButton();
        btnAsiento20 = new javax.swing.JButton();
        btnAsiento21 = new javax.swing.JButton();
        btnAsiento22 = new javax.swing.JButton();
        btnAsiento23 = new javax.swing.JButton();
        btnAsiento24 = new javax.swing.JButton();
        btnAsiento25 = new javax.swing.JButton();
        btnAsiento26 = new javax.swing.JButton();
        btnAsiento27 = new javax.swing.JButton();
        btnAsiento28 = new javax.swing.JButton();
        btnAsiento29 = new javax.swing.JButton();
        btnAsiento30 = new javax.swing.JButton();
        btnAsiento31 = new javax.swing.JButton();
        btnAsiento32 = new javax.swing.JButton();
        btnAsiento33 = new javax.swing.JButton();
        btnAsiento34 = new javax.swing.JButton();
        btnAsiento35 = new javax.swing.JButton();
        panelFooter = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panelTipoEntrada = new javax.swing.JPanel();
        lblAdulto = new javax.swing.JLabel();
        panelEntradaAdulto = new javax.swing.JPanel();
        btnRestaAdulto = new javax.swing.JButton();
        lblContadorAdulto = new javax.swing.JLabel();
        btnSumaAdulto = new javax.swing.JButton();
        lblAdultoMayor = new javax.swing.JLabel();
        panelEntradaAdultoM = new javax.swing.JPanel();
        btnRestaAdultoM = new javax.swing.JButton();
        lblContadorAdultoM = new javax.swing.JLabel();
        btnSumaAdultoM = new javax.swing.JButton();
        lblNiños = new javax.swing.JLabel();
        panelEntradaNiños = new javax.swing.JPanel();
        btnRestaNiños = new javax.swing.JButton();
        lblContadorNiños = new javax.swing.JLabel();
        btnSumaNiños = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(930, 800));
        setMinimumSize(new java.awt.Dimension(930, 800));
        setPreferredSize(new java.awt.Dimension(930, 800));

        panelPantalla.setBackground(new java.awt.Color(102, 102, 102));
        panelPantalla.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelPantalla.setMaximumSize(new java.awt.Dimension(930, 70));
        panelPantalla.setMinimumSize(new java.awt.Dimension(930, 70));
        panelPantalla.setPreferredSize(new java.awt.Dimension(930, 70));

        labelPantalla.setBackground(new java.awt.Color(51, 153, 255));
        labelPantalla.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelPantalla.setForeground(new java.awt.Color(255, 255, 255));
        labelPantalla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPantalla.setText("PANTALLA");

        javax.swing.GroupLayout panelPantallaLayout = new javax.swing.GroupLayout(panelPantalla);
        panelPantalla.setLayout(panelPantallaLayout);
        panelPantallaLayout.setHorizontalGroup(
            panelPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPantallaLayout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(labelPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(256, Short.MAX_VALUE))
        );
        panelPantallaLayout.setVerticalGroup(
            panelPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPantallaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelPantalla)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelPantalla, java.awt.BorderLayout.PAGE_START);

        panelDatosPelicula.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panelDatosPelicula.setMaximumSize(new java.awt.Dimension(300, 800));
        panelDatosPelicula.setMinimumSize(new java.awt.Dimension(300, 800));
        panelDatosPelicula.setPreferredSize(new java.awt.Dimension(300, 800));
        panelDatosPelicula.setLayout(new java.awt.GridLayout(10, 4, 2, 5));

        lblTitulo.setText("Título:");
        lblTitulo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15));
        panelDatosPelicula.add(lblTitulo);

        lblTituloData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelDatosPelicula.add(lblTituloData);

        lblCine.setText("Cine:");
        lblCine.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15));
        panelDatosPelicula.add(lblCine);

        lblCineData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelDatosPelicula.add(lblCineData);

        lblFecha.setText("Fecha:");
        lblFecha.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15));
        panelDatosPelicula.add(lblFecha);

        lblFechaData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelDatosPelicula.add(lblFechaData);

        lblHora.setText("Hora:");
        lblHora.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15));
        panelDatosPelicula.add(lblHora);

        lblHoraData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelDatosPelicula.add(lblHoraData);
        panelDatosPelicula.add(filler1);

        getContentPane().add(panelDatosPelicula, java.awt.BorderLayout.LINE_START);

        panelButacas.setBackground(new java.awt.Color(255, 255, 255));
        panelButacas.setLayout(new java.awt.GridLayout(5, 6, 6, 5));

        btnAsiento1.setEnabled(false);
        panelButacas.add(btnAsiento1);

        btnAsiento2.setEnabled(false);
        panelButacas.add(btnAsiento2);

        btnAsiento3.setEnabled(false);
        panelButacas.add(btnAsiento3);

        btnAsiento4.setEnabled(false);
        panelButacas.add(btnAsiento4);

        btnAsiento5.setEnabled(false);
        panelButacas.add(btnAsiento5);

        btnAsiento6.setEnabled(false);
        panelButacas.add(btnAsiento6);

        btnAsiento7.setEnabled(false);
        panelButacas.add(btnAsiento7);

        btnAsiento8.setEnabled(false);
        panelButacas.add(btnAsiento8);

        btnAsiento9.setEnabled(false);
        panelButacas.add(btnAsiento9);

        btnAsiento10.setEnabled(false);
        panelButacas.add(btnAsiento10);

        btnAsiento11.setEnabled(false);
        panelButacas.add(btnAsiento11);

        btnAsiento12.setEnabled(false);
        panelButacas.add(btnAsiento12);

        btnAsiento13.setEnabled(false);
        panelButacas.add(btnAsiento13);

        btnAsiento14.setEnabled(false);
        panelButacas.add(btnAsiento14);

        btnAsiento15.setEnabled(false);
        panelButacas.add(btnAsiento15);

        btnAsiento16.setEnabled(false);
        panelButacas.add(btnAsiento16);

        btnAsiento17.setEnabled(false);
        panelButacas.add(btnAsiento17);

        btnAsiento18.setEnabled(false);
        panelButacas.add(btnAsiento18);

        btnAsiento19.setEnabled(false);
        panelButacas.add(btnAsiento19);

        btnAsiento20.setEnabled(false);
        panelButacas.add(btnAsiento20);

        btnAsiento21.setEnabled(false);
        panelButacas.add(btnAsiento21);

        btnAsiento22.setEnabled(false);
        panelButacas.add(btnAsiento22);

        btnAsiento23.setEnabled(false);
        panelButacas.add(btnAsiento23);

        btnAsiento24.setEnabled(false);
        panelButacas.add(btnAsiento24);

        btnAsiento25.setEnabled(false);
        panelButacas.add(btnAsiento25);

        btnAsiento26.setEnabled(false);
        panelButacas.add(btnAsiento26);

        btnAsiento27.setEnabled(false);
        panelButacas.add(btnAsiento27);

        btnAsiento28.setEnabled(false);
        panelButacas.add(btnAsiento28);

        btnAsiento29.setEnabled(false);
        panelButacas.add(btnAsiento29);

        btnAsiento30.setEnabled(false);
        panelButacas.add(btnAsiento30);

        btnAsiento31.setEnabled(false);
        panelButacas.add(btnAsiento31);

        btnAsiento32.setEnabled(false);
        panelButacas.add(btnAsiento32);

        btnAsiento33.setEnabled(false);
        panelButacas.add(btnAsiento33);

        btnAsiento34.setEnabled(false);
        panelButacas.add(btnAsiento34);

        btnAsiento35.setEnabled(false);
        panelButacas.add(btnAsiento35);

        getContentPane().add(panelButacas, java.awt.BorderLayout.CENTER);

        panelFooter.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 102)));
        panelFooter.setMaximumSize(new java.awt.Dimension(930, 100));
        panelFooter.setMinimumSize(new java.awt.Dimension(930, 100));
        panelFooter.setPreferredSize(new java.awt.Dimension(930, 100));

        jButton1.setText("Atrás");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Connfirmar Selección");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFooterLayout = new javax.swing.GroupLayout(panelFooter);
        panelFooter.setLayout(panelFooterLayout);
        panelFooterLayout.setHorizontalGroup(
            panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFooterLayout.createSequentialGroup()
                .addContainerGap(669, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelFooterLayout.setVerticalGroup(
            panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFooterLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(panelFooter, java.awt.BorderLayout.SOUTH);

        panelTipoEntrada.setMinimumSize(new java.awt.Dimension(200, 800));
        panelTipoEntrada.setPreferredSize(new java.awt.Dimension(200, 800));
        panelTipoEntrada.setLayout(new javax.swing.BoxLayout(panelTipoEntrada, javax.swing.BoxLayout.Y_AXIS));

        lblAdulto.setText("Adulto");
        panelTipoEntrada.add(lblAdulto);

        panelEntradaAdulto.setMaximumSize(new java.awt.Dimension(200, 30));
        panelEntradaAdulto.setMinimumSize(new java.awt.Dimension(200, 30));
        panelEntradaAdulto.setPreferredSize(new java.awt.Dimension(200, 30));
        panelEntradaAdulto.setLayout(new java.awt.GridLayout(1, 1, 3, 0));

        btnRestaAdulto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRestaAdulto.setText("-");
        btnRestaAdulto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaAdultoActionPerformed(evt);
            }
        });
        panelEntradaAdulto.add(btnRestaAdulto);

        lblContadorAdulto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblContadorAdulto.setText("0");
        panelEntradaAdulto.add(lblContadorAdulto);

        btnSumaAdulto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSumaAdulto.setText("+");
        panelEntradaAdulto.add(btnSumaAdulto);

        panelTipoEntrada.add(panelEntradaAdulto);

        lblAdultoMayor.setText("AdultoMayor");
        panelTipoEntrada.add(lblAdultoMayor);

        panelEntradaAdultoM.setMaximumSize(new java.awt.Dimension(200, 30));
        panelEntradaAdultoM.setMinimumSize(new java.awt.Dimension(200, 30));
        panelEntradaAdultoM.setPreferredSize(new java.awt.Dimension(200, 30));
        panelEntradaAdultoM.setLayout(new java.awt.GridLayout(1, 1, 3, 0));

        btnRestaAdultoM.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRestaAdultoM.setText("-");
        btnRestaAdultoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaAdultoMActionPerformed(evt);
            }
        });
        panelEntradaAdultoM.add(btnRestaAdultoM);

        lblContadorAdultoM.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblContadorAdultoM.setText("0");
        panelEntradaAdultoM.add(lblContadorAdultoM);

        btnSumaAdultoM.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSumaAdultoM.setText("+");
        panelEntradaAdultoM.add(btnSumaAdultoM);

        panelTipoEntrada.add(panelEntradaAdultoM);

        lblNiños.setText("Niños");
        panelTipoEntrada.add(lblNiños);

        panelEntradaNiños.setMaximumSize(new java.awt.Dimension(200, 30));
        panelEntradaNiños.setMinimumSize(new java.awt.Dimension(200, 30));
        panelEntradaNiños.setPreferredSize(new java.awt.Dimension(200, 30));
        panelEntradaNiños.setLayout(new java.awt.GridLayout(1, 1, 3, 0));

        btnRestaNiños.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRestaNiños.setText("-");
        btnRestaNiños.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaNiñosActionPerformed(evt);
            }
        });
        panelEntradaNiños.add(btnRestaNiños);

        lblContadorNiños.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblContadorNiños.setText("0");
        panelEntradaNiños.add(lblContadorNiños);

        btnSumaNiños.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSumaNiños.setText("+");
        panelEntradaNiños.add(btnSumaNiños);

        panelTipoEntrada.add(panelEntradaNiños);

        getContentPane().add(panelTipoEntrada, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRestaAdultoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaAdultoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRestaAdultoActionPerformed

    private void btnRestaAdultoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaAdultoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRestaAdultoMActionPerformed

    private void btnRestaNiñosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaNiñosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRestaNiñosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelecciónButacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelecciónButacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelecciónButacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelecciónButacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelecciónButacas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsiento1;
    private javax.swing.JButton btnAsiento10;
    private javax.swing.JButton btnAsiento11;
    private javax.swing.JButton btnAsiento12;
    private javax.swing.JButton btnAsiento13;
    private javax.swing.JButton btnAsiento14;
    private javax.swing.JButton btnAsiento15;
    private javax.swing.JButton btnAsiento16;
    private javax.swing.JButton btnAsiento17;
    private javax.swing.JButton btnAsiento18;
    private javax.swing.JButton btnAsiento19;
    private javax.swing.JButton btnAsiento2;
    private javax.swing.JButton btnAsiento20;
    private javax.swing.JButton btnAsiento21;
    private javax.swing.JButton btnAsiento22;
    private javax.swing.JButton btnAsiento23;
    private javax.swing.JButton btnAsiento24;
    private javax.swing.JButton btnAsiento25;
    private javax.swing.JButton btnAsiento26;
    private javax.swing.JButton btnAsiento27;
    private javax.swing.JButton btnAsiento28;
    private javax.swing.JButton btnAsiento29;
    private javax.swing.JButton btnAsiento3;
    private javax.swing.JButton btnAsiento30;
    private javax.swing.JButton btnAsiento31;
    private javax.swing.JButton btnAsiento32;
    private javax.swing.JButton btnAsiento33;
    private javax.swing.JButton btnAsiento34;
    private javax.swing.JButton btnAsiento35;
    private javax.swing.JButton btnAsiento4;
    private javax.swing.JButton btnAsiento5;
    private javax.swing.JButton btnAsiento6;
    private javax.swing.JButton btnAsiento7;
    private javax.swing.JButton btnAsiento8;
    private javax.swing.JButton btnAsiento9;
    private javax.swing.JButton btnRestaAdulto;
    private javax.swing.JButton btnRestaAdultoM;
    private javax.swing.JButton btnRestaNiños;
    private javax.swing.JButton btnSumaAdulto;
    private javax.swing.JButton btnSumaAdultoM;
    private javax.swing.JButton btnSumaNiños;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelPantalla;
    private javax.swing.JLabel lblAdulto;
    private javax.swing.JLabel lblAdultoMayor;
    public javax.swing.JLabel lblCine;
    private javax.swing.JLabel lblCineData;
    private javax.swing.JLabel lblContadorAdulto;
    private javax.swing.JLabel lblContadorAdultoM;
    private javax.swing.JLabel lblContadorNiños;
    public javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaData;
    public javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblHoraData;
    private javax.swing.JLabel lblNiños;
    public javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloData;
    private javax.swing.JPanel panelButacas;
    private javax.swing.JPanel panelDatosPelicula;
    private javax.swing.JPanel panelEntradaAdulto;
    private javax.swing.JPanel panelEntradaAdultoM;
    private javax.swing.JPanel panelEntradaNiños;
    private javax.swing.JPanel panelFooter;
    private javax.swing.JPanel panelPantalla;
    private javax.swing.JPanel panelTipoEntrada;
    // End of variables declaration//GEN-END:variables
}
